

function selectCharacter(character){
	document.getElementById('nameCharacter').innerHTML = character;

	if(character =='galexy'){
	  document.getElementById('imgCharacter').src = 'pic/galexy.png';
	document.getElementById('Highlights').innerHTML ='<font  color="aqua" size="4">Highlights</font>: <br><br><center>Icy Nights Trap video mix <br><br><iframe width="560" height="315" src="https://www.youtube.com/embed/MAXoGQ5mZrc" frameborder="0" allowfullscreen></iframe><br><br>Faded Sunrise<br><iframe width="100%" height="100" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/290227313&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br><br>Racer Remixed Playlist <br><iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PL31EC2F6597EEE8A1" frameborder="0" allowfullscreen></iframe><br>Falling Stars<br><iframe width="100%" height="100" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/324652775&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe></center>';
	document.getElementById('Music').innerHTML = '<font  color="aqua" size="4">Music</font>: <center>Soundcloud:</center><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/70478132&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br><center><br>"Pokemon Go Theme" Psychic Type - Indigo Plateau (galexy edit)<br><iframe width="560" height="315" src="https://www.youtube.com/embed/SVnk8k41ENQ" frameborder="0" allowfullscreen></iframe></center>';
	document.getElementById('Videos').innerHTML = '<font  color="aqua" size="4">Videos</font>: <br><br><center></iframe><br>Uploads<br><iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=UUsSvDTKToE_9BgHjmWOw5UA" frameborder="0" allowfullscreen></iframe><br><br>DIVINITY DROP<br><br><iframe width="560" height="315" src="https://www.youtube.com/embed/W52LgLB2fBY" frameborder="0" allowfullscreen></iframe><br><br>Icy Nights Trap video mix <br><iframe width="560" height="315" src="https://www.youtube.com/embed/MAXoGQ5mZrc" frameborder="0" allowfullscreen></iframe><br><br>Cyber Sex on the Beach Video Mix <br><iframe width="560" height="315" src="https://www.youtube.com/embed/TD907yN9bxc" frameborder="0" allowfullscreen></iframe></center>';
	document.getElementById('Other').innerHTML = '<font  color="aqua" size="4">Podcasts</font>: <center>Roomies<br><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/319791003&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br><br><br>';
	}
	if(character =='demigod'){
	  document.getElementById('imgCharacter').src = 'pic/demigod.png';
	document.getElementById('Highlights').innerHTML = '<font  color="aqua" size="4">Highlights</font>:<center>do y0u have some time for me?<br><br><iframe width="560" height="315" src="https://www.youtube.com/embed/Wz26kxCdkzg" frameborder="0" allowfullscreen></iframe><br><br>Dumb Like a Moron<br><iframe width="560" height="315" src="https://www.youtube.com/embed/vzTHergfbkY?list=UUZNmIsZNT54fxGPoedt6yMQ" frameborder="0" allowfullscreen></iframe><br><br>demigod james - played 3 times<br><iframe width="100%" height="150" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/338580698&amp;color=00cc11&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br><br>listening to the bladerunner soundtrack a lot. this has nothing to do with that.<br><iframe width="100%" height="150" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/338579983&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br>';
	document.getElementById('Music').innerHTML = '<font  color="aqua" size="4">Music</font>: <center>Soundcloud:</center><br><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/88194134&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>';
	document.getElementById('Videos').innerHTML = '<font  color="aqua" size="4">Videos</font>: <br><br><center></iframe><br>Uploads<br><iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=UUZNmIsZNT54fxGPoedt6yMQ" frameborder="0" allowfullscreen></iframe><br><br><iframe width="560" height="315" src="https://www.youtube.com/embed/TJ2sJbKL_v8" frameborder="0" allowfullscreen></iframe><br></center>';
	document.getElementById('Other').innerHTML = '';
	}
	
	if(character =='TanTeburu'){
	  document.getElementById('imgCharacter').src = 'pic/TanTeburu.png';
	document.getElementById('Highlights').innerHTML = '<font  color="aqua" size="4">Highlights</font>: <center>Akiras Heart<br><iframe width="560" height="315" src="https://www.youtube.com/embed/6wHxnGYEGv4" frameborder="0" allowfullscreen></iframe><br><br>Tan-Teburu - TMNT<br><iframe width="560" height="315" src="https://www.youtube.com/embed/t-BH5kiSYcY" frameborder="0" allowfullscreen></iframe><br><br>Surface Noise Beattape<br><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/338314051&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br><br>Space Pirates<br><iframe width="560" height="315" src="https://www.youtube.com/embed/zl0rHGTPMh4" frameborder="0" allowfullscreen></iframe></center>';
	document.getElementById('Music').innerHTML = '<font  color="aqua" size="4">Music</font>: <center>Soundcloud:<br><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/156238992&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br<br><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/244670268&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br><br>Tan Teburu<br><iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLl-ANqBu28GP7n-0gNiUIwUy9Ka2ZIqv9" frameborder="0" allowfullscreen></iframe><br><br></center>';
	document.getElementById('Videos').innerHTML = '<font  color="aqua" size="4">Videos</font>: <br><br><center>Uploads<br><iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLl-ANqBu28GPvVxCt2oo87LXZeKUGDUHy" frameborder="0" allowfullscreen></iframe><br><br><center>~~VA-POR-VIEW~~<br><iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLl-ANqBu28GP2QHNQ-Y1Fuo0OqmqKVmzA" frameborder="0" allowfullscreen></iframe><br><br><br><center>Champloo mix<br><iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLl-ANqBu28GNfKBGktS5OByUh8i7Us0xE" frameborder="0" allowfullscreen></iframe><br>';
	document.getElementById('Other').innerHTML = ''
	}
	
	if(character =='G'){
	  document.getElementById('imgCharacter').src = 'pic/G.png';
	document.getElementById('Highlights').innerHTML = '<font  color="aqua" size="4">Highlights</font>: <center>Sword of a Stranger a Stranger AMV (Final Fight)<br><iframe width="560" height="315" src="https://www.youtube.com/embed/4ae2q9sCPA8?list=UUs2pRBh3xQa762hIqTn0IlQ" frameborder="0" allowfullscreen></iframe><br><br>Afro Samurai Resurrection AMV [Edit Part 1]<br><iframe width="560" height="315" src="https://www.youtube.com/embed/OLbLBZpS6I8?list=UUs2pRBh3xQa762hIqTn0IlQ" frameborder="0" allowfullscreen></iframe><br><br>Korra Season 2 Finale AMV<br><iframe width="560" height="315" src="https://www.youtube.com/embed/L383XMa5RwE?list=UUs2pRBh3xQa762hIqTn0IlQ" frameborder="0" allowfullscreen></iframe><br></iframe>';
	document.getElementById('Videos').innerHTML = '<font  color="aqua" size="4">Videos</font>:<br><br><center>Uploads<br><iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=UUs2pRBh3xQa762hIqTn0IlQ" frameborder="0" allowfullscreen></iframe><br><br>';
	document.getElementById('Music').innerHTML = ' ';
	document.getElementById('Other').innerHTML = ''
	}
		if(character =='Pinky'){
	  document.getElementById('imgCharacter').src = 'pic/Pinky.png';
	document.getElementById('Highlights').innerHTML = '<font  color="aqua" size="4">Highlights</font>: <center>Pinky - Whenever<br><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/318403941&amp;color=ff00ba&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br><br>Pinky - Life<br><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/303582542&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br><br>Pinky - The Hitchcock Project<br><iframe width="560" height="315" src="https://www.youtube.com/embed/-gXr4iX_bGY" frameborder="0" allowfullscreen></iframe>';
		document.getElementById('Music').innerHTML = '<font  color="aqua" size="4">Music</font>:<br><br><center>Uploads<br><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users/16412651&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe><br>';
	document.getElementById('Videos').innerHTML = '<font  color="aqua" size="4">Videos</font>:<br><br><center>Uploads<br><iframe width="560" height="315" src="https://www.youtube.com/embed/eI7sE04GgKE?list=UUEBTV2dwGJ-35SDb3Vl7aQQ" frameborder="0" allowfullscreen></iframe><br><br>';

	document.getElementById('Other').innerHTML = ''
	} 


	
	
	


}